color: null
fieldLayouts:
  ca66cd4e-fdc8-40db-851d-0fdca7dc3060:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-10T13:46:14+00:00'
            elementCondition: null
            fieldUid: fa96ef04-de26-4eaf-82db-302460849f80 # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4583bea3-0b83-468b-b7e6-d4f5e3b17c5a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T13:46:14+00:00'
            elementCondition: null
            fieldUid: f8097071-b43d-4db1-868b-11799910e0bf # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d57d87c-f9b8-4a9a-9eec-bfc36974dd17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-10T13:46:14+00:00'
            elementCondition: null
            fieldUid: 67fc1874-b3bb-47cc-b963-f87ade348930 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0befeba6-d89d-4cd0-afa7-fef9558da6b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a095fc6b-e783-45d3-b096-e946fed7a127
        userCondition: null
handle: menuItem
hasTitleField: false
icon: null
name: 'Menu item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{mxTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
