altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  25f0c55a-ebe6-4cc2-a6c3-5882bf6e8a3a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-13T07:09:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3c1caae6-f1c8-424c-9ce7-425921a160af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df6bc149-c319-4fdd-af64-026c4acd7e25
        userCondition: null
fs: assets
handle: assets
name: assets
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
