altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  04aa856d-5b82-4dcb-a20f-1731df1ee134:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-10T13:41:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5a25bfcc-33ff-4a32-8244-1eda643d48e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cfafcbbf-e040-4e92-8f7c-0de47e2b60aa
        userCondition: null
fs: images
handle: images
name: images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
