columnSuffix: null
handle: homeIntroText
instructions: null
name: 'Intro text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: null
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
