dateModified: 1736512999
email:
  fromEmail: collinvdv@gmail.com
  fromName: dkd
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    41bbb680-9ece-40db-9dd6-9be9452ef0bc: dkd # dkd
    a72ef1f9-47e8-4f22-90ae-e6cf20d67a83: dkd # dkd
system:
  edition: solo
  live: true
  name: dkd
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
